version: "3.9"

services:
  codedaily-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codedaily-web
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - ./prisma:/app/prisma
      - ./content:/app/content
    restart: unless-stopped